report/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('report_app.urls')),
    path('', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report_app/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

from . import views

app_name = 'report_app'

urlpatterns = [
    path('', views.csp_login, name='login'),
    path('logout/', views.csp_logout, name='csp_logout'),
    path('notlogin/', views.notlogin, name='notlogin'),
    path('reports/', views.reports, name='reports'),
    # path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('change_password/',views.change_password,name='password_change'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Dashboard</title>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_dashboard.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/alertmsgcss.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>


    <!-- datatable -->


    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.11/sorting/date-eu.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <!-- <script src="https://cdn.datatables.net/fixedcolumns/3.3.2/js/dataTables.fixedColumns.min.js" type="text/javascript"></script> -->
    <!-- datatable end -->
    <style>
        .multiselect {
            width: 200px;
            margin-right: 20px;
            /* margin-bottom: 5px; */
        }

        .selectBox {
            position: relative;
        }

        .selectBox select {
            width: 100%;
            font-weight: 400;
        }

        .overSelect {
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
        }

    </style>
    <!-- {#    <style>#}
    {#        .MultiCheckBox {#}
    {#            border: 1px solid #e2e2e2;#}
    {#            padding: 5px;#}
    {#            border-radius: 4px;#}
    {#            cursor: pointer;#}
    {#        }#}
    {##}
    {#        .MultiCheckBox .k-icon {#}
    {#            font-size: 15px;#}
    {#            float: right;#}
    {#            font-weight: bolder;#}
    {#            margin-top: -7px;#}
    {#            height: 10px;#}
    {#            width: 14px;#}
    {#            color: #787878;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetail {#}
    {#            display: none;#}
    {#            position: absolute;#}
    {#            border: 1px solid #e2e2e2;#}
    {#            overflow-y: hidden;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetailBody {#}
    {#            overflow-y: scroll;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetail .cont {#}
    {#            clear: both;#}
    {#            overflow: hidden;#}
    {#            padding: 2px;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetail .cont:hover {#}
    {#            background-color: #cfcfcf;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetailBody > div > div {#}
    {#            float: left;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetail > div > div:nth-child(1) {#}
    {##}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetailHeader {#}
    {#            overflow: hidden;#}
    {#            position: relative;#}
    {#            height: 28px;#}
    {#            background-color: #3d3d3d;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetailHeader > input {#}
    {#            position: absolute;#}
    {#            top: 4px;#}
    {#            left: 3px;#}
    {#        }#}
    {##}
    {#        .MultiCheckBoxDetailHeader > div {#}
    {#            position: absolute;#}
    {#            top: 5px;#}
    {#            left: 24px;#}
    {#            color: #fff;#}
    {#        }#}
    {#    </style>#} -->


</head>
<body>
<div class="wrapper collapse">
    <div class="top_navbar">
        <div class="top_menu">
            <div class="logo" style="padding-left: 2%; width:0px">

                <a href=""><img src="{% static 'images/udaanredlogo.png' %}" alt="Company Logo" style="width: 50px;"
                                title="Refresh"></a></div>

            <div class="user-div">
                <ul>
                    <li><a href="{% url 'report_app:password_change' %}" title="Change Password for {{ request.user }}"><i class="fas fa-user-lock"></i></a></li>
                
                    <li title="Logout"><a href="{% url 'report_app:csp_logout' %}"><i
                            class="fas fa-sign-out-alt"></i></a></li>
                </ul>
            </div>
        </div>
    </div>


    <div class="main_container" style="margin-left: 0px;width:calc(100% - 20px);">

  
        <div class="item item_contents">

            {% block tabcontentblock %}


            {% endblock %}
            <div style="padding: 100px; width: inherit;">

            </div>
            {% if messages %}
                {% for msg in messages %}
                    {% if msg.tags == 'success' %}
                        <div id="alerts"
                             class="alert alert-success alert-dismissible sucess-msg-alert animate__animated animate__slideInRight animate__fast">
                            <table id="success-tbl">
                                <tr>
                                    <td rowspan="2"><i class="fas fa-check-circle"
                                                       style="padding: 15px; padding-left: 0px !important;"></i></td>
                                    <td style="font-size: 16px; font-weight: bold;">Success</td>
                                </tr>
                                <tr>
                                    <td>{{ msg }}</td>

                                </tr>
                            </table>
                            <button type="button" class="close" data-dismiss="alert" style="outline: none !important;">
                                &times;
                            </button>

                        </div>
                    {% endif %}
                    {% if msg.tags == 'error' %}
                        <div id="alerts"
                             class="alert alert-danger alert-dismissible error-msg-alert animate__animated animate__slideInRight animate__fast">
                            <table id="failure-tbl">
                                <tr>
                                    <td rowspan="2" style="border-bottom: none;"><i class="fas fa-times"
                                                                                    style="padding: 15px; padding-left: 0px !important; font-family: 'Font Awesome 5 Free' !important;"></i>
                                    </td>
                                    <td style="font-size: 16px; font-weight: bold;border-bottom: none;">Error</td>

                                </tr>
                                <tr>
                                    <td style="border-bottom: none;">{{ msg }}</td>
                                </tr>
                            </table>
                            <button type="button" class="close" data-dismiss="alert" style="outline: none !important;">
                                &times;
                            </button>

                        </div>
                    {% endif %}
                    {% if msg.tags == 'warning' %}
                        <div id="alerts"
                             class="alert alert-warning alert-dismissible warning-msg-alert animate__animated animate__slideInRight animate__fast">
                            <table id="warning-tbl">
                                <tr>
                                    <td rowspan="2" style="border-bottom: none;"><i class="fas fa-times"
                                                                                    style="padding: 15px; padding-left: 0px !important; font-family: 'Font Awesome 5 Free' !important;"></i>
                                    </td>
                                    <td style="font-size: 16px; font-weight: bold;border-bottom: none;">Warning</td>

                                </tr>
                                <tr>
                                    <td style="border-bottom: none;">{{ msg }}</td>
                                </tr>
                            </table>
                            <button type="button" class="close" data-dismiss="alert" style="outline: none !important;">
                                &times;
                            </button>

                        </div>
                    {% endif %}

                {% endfor %}
            {% endif %}


        </div>

    </div>
</div>
<script type="text/javascript">
    function hidediv(stay) {

        console.log(stay);
        if (stay != 0) {
            console.log('in');
            $('#alerts').removeClass('animate__animated animate__slideOutRight animate__fast').show().addClass('animate__animated animate__slideInRight animate__fast');

            $('#alerts').removeClass('animate__animated animate__slideInRight animate__fast').addClass('animate__animated animate__slideOutRight animate__fast');

        } else {
            console.log('Dont Go');
        }

    }


    $("#alerts").hover(function () {
            setTimeout("hidediv(0)", 2000);
        },
        function () {
            setTimeout("hidediv(1)", 2000);
        }
    );
    setTimeout("hidediv(1)", 2000);

    function donthide() {
        console.log('okay');
    }


</script>


</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/alertmsgcss.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<body>
<div class="login-wrapper">
    {% block bodyblock %}

        <div>
            <h2 style="color: #bf0711;">Login</h2>
        </div>

        <form method="POST">
            {% csrf_token %}
            <div class="login-input-holder">
                <input type="text" placeholder="Username" class="login-input" name="username">
            </div>
            <div class="login-input-holder">
                <input type="password" placeholder="Password" class="login-input" name="password">
            </div>
            <div class="login-btn-holder" style="padding-bottom: 10px;">
                <button class="login-btn" formaction="{% url 'report_app:login' %}" type="submit">Login</button>
            </div>
            <div class="login-btn-holder" style="padding-top: 0px;">
                <a href="/password_reset/">Forgot Password?</a>
                {% if messages %}
                    {% for msg in messages %}
                        {% if msg.tags == 'success' %}
                            <div id="alerts"
                                 class="alert alert-success alert-dismissible sucess-msg-alert animate__animated animate__slideInRight animate__fast"
                                 style="    right: -37vw;
                        bottom: -20vh;
                    ">
                                <table id="success-tbl">
                                    <tr>
                                        <td rowspan="2"><i class="fas fa-check-circle"
                                                           style="padding: 15px; padding-left: 0px !important;"></i>
                                        </td>
                                        <td style="font-size: 16px; font-weight: bold;">Success</td>
                                    </tr>
                                    <tr>
                                        <td>{{ msg }}</td>

                                    </tr>
                                </table>
                                <button type="button" class="close" data-dismiss="alert"
                                        style="outline: none !important;"> &times;
                                </button>

                            </div>
                        {% endif %}
                        {% if msg.tags == 'error' %}
                            <div id="alerts"
                                 class="alert alert-danger alert-dismissible error-msg-alert animate__animated animate__slideInRight animate__fast"
                                 style="    right: -37vw;
                        bottom: -20vh;
                    ">
                                <table id="failure-tbl">
                                    <tr>
                                        <td rowspan="2" style="border-bottom: none;"><i class="fas fa-times"
                                                                                        style="padding: 15px; padding-left: 0px !important; font-family: 'Font Awesome 5 Free' !important;"></i>
                                        </td>
                                        <td style="font-size: 16px; font-weight: bold;border-bottom: none;">Error</td>

                                    </tr>
                                    <tr>
                                        <td style="border-bottom: none;">{{ msg }}</td>
                                    </tr>
                                </table>
                                <button type="button" class="close" data-dismiss="alert"
                                        style="outline: none !important;">&times;
                                </button>

                            </div>
                        {% endif %}
                        {% if msg.tags == 'warning' %}
                            <div id="alerts"
                                 class="alert alert-warning alert-dismissible warning-msg-alert animate__animated animate__slideInRight animate__fast"
                                 style="    right: -37vw;
                        bottom: -20vh;
                    ">
                                <table id="warning-tbl">
                                    <tr>
                                        <td rowspan="2" style="border-bottom: none;"><i class="fas fa-times"
                                                                                        style="padding: 15px; padding-left: 0px !important; font-family: 'Font Awesome 5 Free' !important;"></i>
                                        </td>
                                        <td style="font-size: 16px; font-weight: bold;border-bottom: none;">Warning</td>

                                    </tr>
                                    <tr>
                                        <td style="border-bottom: none;">{{ msg }}</td>
                                    </tr>
                                </table>
                                <button type="button" class="close" data-dismiss="alert"
                                        style="outline: none !important;">&times;
                                </button>

                            </div>
                        {% endif %}

                    {% endfor %}
                {% endif %}

            </div>
        </form>
    {% endblock %}
</div>
<script type="text/javascript">
    function hidediv() {
        $('#alerts').removeClass('animate__animated animate__slideOutRight animate__fast').show().addClass('animate__animated animate__slideInRight animate__fast');

        $('#alerts').removeClass('animate__animated animate__slideInRight animate__fast').addClass('animate__animated animate__slideOutRight animate__fast');
    }

    setTimeout("hidediv()", 2000);


</script>
</body>
</html>

templates/previous.html
<div style="padding-top: 60px;padding-bottom:10px;display: flex;justify-content: space-between;">
    <label>RESPONSE HEADERS</label>
    <br>
</div>

<form id="payroll_form" method="post">
    {% csrf_token %}
    <div>
        <style>
            .data_table td {
                padding: 5px;
                margin: 5px;
                font-size: initial;
                width: -moz-available;
            }

            .data_table text {
                padding: 5px;
                margin: 5px;
                font-size: initial;
            }

            .sub_table {
                font-size: initial;
                width: 200px;
            }
        </style>
        <table class="data_table" style="overflow-x: auto; white-space: nowrap;" onmouseover="this.style.display='block'"
        onmouseout="this.style.display='' ">
            <thead>
            <tr>
                <td>Dimensions :</td>
                {% for dimension in dimensions %}
                    <td>
                        <div class="multiselect">
                            <div class="selectBox"
                                 onclick="showCheckboxes('div--{{ dimension.name }}--{{ forloop.counter }}')">
                                <select name="dimensions" class="dimensions"
                                        id="dimensions--{{ forloop.counter }}" style="font-size: initial">
                                    <option>{{ dimension.name }}</option>
                                </select>
                                <div class="overSelect"></div>
                            </div>
                            <div id="div--{{ dimension.name }}--{{ forloop.counter }}" style="display: none;
    border: 1px #dadada solid;">
                                {% with var1=dimension.fk_table.db_table_name var2=dimension.fk_table.sort_column %}
                                    {% define var1|add:'--'|add:var2|get_sub_field as query_set %}
                                    {% for name,fk in query_set.query_set.items %}
                                        <label for="{{ name }}--{{ forloop.counter }}--{{ forloop.parentloop.counter }}"
                                               style="display: block; ">
                                            <input type="checkbox" class="{{ dimension.name }}"
                                                   name="{{ name }}--{{ query_set.pk_set|get_dict_value:name }}--{{ dimension.name }}"
                                                   id="{{ dimension.name }}--{{ fk }}--{{ query_set.pk_set|get_dict_value:name }}"
                                                   onclick="fetch_dependent_field(this.id)"/>{{ name }}
                                        </label>
                                    {% endfor %}
                                {% endwith %}
                            </div>
                        </div>
<!-- 

                        {#                                <select name="dimensions" class="dimensions" id="dimensions--{{ forloop.counter }}"#}
                        {#                                        style="width: auto" multiple>#}
                        {#                                    {% with var1=dimension.fk_table.db_table_name var2=dimension.fk_table.sort_column %}#}
                        {#                                        {% define var1|add:'--'|add:var2|get_sub_field as query_set %}#}
                        {#                                        {% for name in query_set %}#}
                        {#                                            <option value="{{ name }}"#}
                        {#                                                    id="period--{{ forloop.counter }}--{{ forloop.parentloop.counter }}">#}
                        {#                                                {{ name }}#}
                        {#                                            </option>#}
                        {#                                        {% endfor %}#}
                        {#                                    {% endwith %}#}
                        {#                                </select>#}
                        {#                                <script>#}
                        {#                                    $(document).ready(function () {#}
                        {#                                        $("#dimensions--{{ forloop.counter }}").CreateMultiCheckBox({#}
                        {#                                            width: '230px',#}
                        {#                                            defaultText: '{{dimension.name}}',#}
                        {#                                            height: '250px'#}
                        {#                                        });#}
                        {#                                    });#}
                        {#                                </script>#} -->
                    </td>
                {% endfor %}

            </tr>
            {#multiple class="chosen-select"#}
            <tr>
                <td>Report Type :</td>
                <td><select data-placeholder="Begin typing a name to filter..."
                            class='sub_table' name="report type" id="type_code">
                    {% for report in report_types %}
                        <option value="{{ report.name }}" style="outline: none !important;">
                            {{ report.name }}
                        </option>
                    {% endfor %}
                </select>
                </td>
            </tr>
            <tr>
                <td>Frequency :</td>
                <td>
                    <select name="frequency" id="freq_code" class='sub_table'>
                        {% for frequency in frequencies %}
                            <option value="{{ frequency.name }}"
                                    style="outline: none !important;">{{ frequency.name }}</option>
                        {% endfor %}
                    </select></td>
            </tr>
            </thead>
            <tbody id="input_data">
            </tbody>
        </table>
    </div>

    <br><br>

    <button type="submit" class="basic-save-btn" id="render_table" name="go_button"
            style="width: 100px;padding: 5px;margin: 5px;float: right">GO
    </button>
    <br>
    <br>

    <tr>
        <td>Dimensions :</td>
        {% for dimension in dimensions %}
            <td>
                <div class="multiselect">
                    <div class="selectBox"
                         onclick="showCheckboxes('div--{{ dimension.name }}--{{ forloop.counter }}')">
                        <select name="dimensions" class="dimensions"
                                id="dimensions--{{ forloop.counter }}" style="font-size: initial">
                            <option>{{ dimension.name }}</option>
                        </select>
                        <div class="overSelect"></div>
                    </div>
                    <div id="div--{{ dimension.name }}--{{ forloop.counter }}" style="display: none;
border: 1px #dadada solid;">
                        {% with var1=dimension.fk_table.db_table_name var2=dimension.fk_table.sort_column %}
                            {% define var1|add:'--'|add:var2|get_sub_field as query_set %}
                            {% for name,fk in query_set.query_set.items %}
                                <label for="{{ name }}--{{ forloop.counter }}--{{ forloop.parentloop.counter }}"
                                       style="display: block; ">
                                    <input type="checkbox" class="{{ dimension.name }}"
                                           name="{{ name }}--{{ query_set.pk_set|get_dict_value:name }}--{{ dimension.name }}"
                                           id="{{ dimension.name }}--{{ fk }}--{{ query_set.pk_set|get_dict_value:name }}"
                                           onclick="fetch_dependent_field(this.id)"/>{{ name }}
                                </label>
                            {% endfor %}
                        {% endwith %}
                    </div>
                </div>
<!-- 

                {#                                <select name="dimensions" class="dimensions" id="dimensions--{{ forloop.counter }}"#}
                {#                                        style="width: auto" multiple>#}
                {#                                    {% with var1=dimension.fk_table.db_table_name var2=dimension.fk_table.sort_column %}#}
                {#                                        {% define var1|add:'--'|add:var2|get_sub_field as query_set %}#}
                {#                                        {% for name in query_set %}#}
                {#                                            <option value="{{ name }}"#}
                {#                                                    id="period--{{ forloop.counter }}--{{ forloop.parentloop.counter }}">#}
                {#                                                {{ name }}#}
                {#                                            </option>#}
                {#                                        {% endfor %}#}
                {#                                    {% endwith %}#}
                {#                                </select>#}
                {#                                <script>#}
                {#                                    $(document).ready(function () {#}
                {#                                        $("#dimensions--{{ forloop.counter }}").CreateMultiCheckBox({#}
                {#                                            width: '230px',#}
                {#                                            defaultText: '{{dimension.name}}',#}
                {#                                            height: '250px'#}
                {#                                        });#}
                {#                                    });#}
                {#                                </script>#} -->
            </td>
        {% endfor %}

    </tr>


    <form id="payroll_form" method="post">
        {% csrf_token %}
        <div>
            <style>
                .data_table td {
                    padding: 5px;
                    margin: 5px;
                    font-size: initial;
                    width: -moz-available;
                }

                .data_table text {
                    padding: 5px;
                    margin: 5px;
                    font-size: initial;
                }

                .sub_table {
                    font-size: initial;
                    width: 200px;
                }
            </style>
            <table class="data_table" style="overflow-x: auto; white-space: nowrap;" onmouseover="this.style.display='block'"
            onmouseout="this.style.display='' ">
                <thead>
                
                {#multiple class="chosen-select"#}
                <tr>
                    <td>Report Type :</td>
                    <td><select data-placeholder="Begin typing a name to filter..."
                                class='sub_table' name="report type" id="type_code">
                        {% for report in report_types %}
                            <option value="{{ report.name }}" style="outline: none !important;">
                                {{ report.name }}
                            </option>
                        {% endfor %}
                    </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>Frequency :</td>
                    <td>
                        <select name="frequency" id="freq_code" class='sub_table'>
                            {% for frequency in frequencies %}
                                <option value="{{ frequency.name }}"
                                        style="outline: none !important;">{{ frequency.name }}</option>
                            {% endfor %}
                        </select></td>
                </tr>
                </thead>
                <tbody id="input_data">
                </tbody>
            </table>
        </div>

        <br><br>
    </form>

</form>

templates/timeout.html
<html>
<body>
    <h2>Please <a href="{% url 'report_app:login' %}"> Login </a> To continue. </h2>



</body>
</html>